version: '3.8'
services:
  go:
    build: ./go
    container_name: go-server
    ports:
      - "9090:8080"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=1234
      - DATABASE_NAME=bookroom_db
    restart: unless-stopped

  fastapi-server:
    build: ./python
    container_name: fastapi-server
    ports:
      - "9000:8000"
    depends_on:
      - go
    environment:
      GO_SERVER_URL: "http://go-server:8080"
    restart: unless-stopped
  
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "1234"         # Password per l'utente root
      MYSQL_DATABASE: "bookroom_db"      # Nome del database creato automaticamente       
    ports:
      - "3308:3306"  # Mappa la porta 3306 del container alla porta 3308 dell'host

    volumes:
      - ./db-data:/var/lib/mysql  # Volume per salvare i dati del database
